# Generated by Django 4.0 on 2022-01-07 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0003_answer_quthor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='quthor',
            new_name='author',
        ),
    ]
